# Generated by Django 4.2.7 on 2024-08-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webapp'),
        ),
    ]
