# Generated by Django 4.2.7 on 2024-08-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_formationcert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formationcert',
        ),
    ]
